### ISSUE TITLE
Debugging Typescript files in VS Code opens compiled file, not original

### ISSUE THREAD

**Issue by phoenixeliot** [swc-project/jest#61]
Reproduction steps:
1. Clone [this test repo](https://github.com/phoenixeliot/line-puzzle) and check out [this commit](https://github.com/phoenixeliot/line-puzzle/commit/6f8ee47271bf0814ca4b05fcfc239e33b1ce467e)
2. Switch to Node v16 if you have multiple installed
3. Run `yarn`
4. Open the repo in VS Code: `code .`
5. Open `src/Board.ts` in an editor (for comparison later)
5. Open a new javascript debug terminal: Open command palette (ctrl/cmd-shift-p), search "debug terminal"
6. In the JS debug terminal, run `jest -- tests/Board.test.ts`

Result: When it pauses on a particular `debugger` line, VS Code will open a new, different Board.ts which seems to be the compiled result (and is definitely not typescript). The debugger will step through that file instead of the original.

I have these sourcemap settings enabled:

jest.config.js:
```js
/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  preset: "ts-jest",
  transform: {
    "^.+\\.(t|j)sx?$": ["@swc/jest", { sourceMaps: true }],
    // "^.+\\.jsx?$": "babel-jest",
    // "^.+\\.tsx?$": "ts-jest",
  },
  testEnvironment: "node",
  testMatch: ["**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).?(m)[jt]s?(x)"],
  moduleFileExtensions: ["js", "jsx", "ts", "tsx", "mjs"],
  setupFiles: ["./tests/setupTests.ts"],
};
```
.swcrc:
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2021"
  },
  "sourceMaps": true
}
```

The problem occurs the same way if I remove `.swcrc`. Same if I remove the sourceMaps option from jest.config.js. Same if I remove the `preset` rule in jest.config.js, which seems to do nothing if I include the transform rule (I accidentally left it in from before). If I remove the `transform` rule entirely as well as the preset, Jest just breaks (doesn't transpile files enough to run them).

This project is set up using Next.js, which may have some other configuration stuff affecting SWC, as Next.js uses SWC. Before adding @swc/jest myself, it wasn't using SWC on Jest (at least, judging by the 2x speedup I got from switching).

Note that debugging with sourceMaps DOES show the original source correctly when running the Next.js application through eg `yarn run next` in the VS Code debugger and with the browser.

Confusingly, the compiled output I get is different (seemingly targeting an older ES version) when I re-clone my repo and reproduce this, but the problem is still essentially the same. No idea what would cause that difference.

**Comment by phoenixeliot** [comment]
https://github.com/swc-project/jest/issues/53

I found similarly that I needed to use sourceMaps: "inline" for this to work. Can we make this the default setting, or add this clearly to the setup documentation?

**Comment by kdy1** [comment]
This should not be default as swc option is mized by `@swc/core`.
I think documentation should be improved.

**Comment by phoenixeliot** [comment]
(what does "mized by" mean? or "mixed by" if that was a typo?)

**Comment by kdy1** [comment]
It's `mixed`. 
But this is fixed.

**Comment by denik1981** [comment]
So, `sourceMaps: "inline"` seems the only way to help the debugger stop at defined breakpoints?
I'm not sure if I have followed well the conversation in this thread, but I can confirm that without `sourceMaps: "inline"` all of my breakpoints are passed alone.

**Comment by jianwu** [comment]
Struggled with this issue many days when debugging grafana-plugin tsx files, intellij never hits the break points. Finally I solved this issue when saw suggestions from this bug. I have to make two changes to make it work: 
1. In `jest.config.js`: change `sourceMaps: "inline"` from `sourceMaps: true`
2. In `tsconfig.json`: add `"inlineSourceMap": true` for `compilerOptions`

**Comment by andreujuanc** [comment]
```
 Validation Warning:

  Unknown option "sourceMaps" with value "inline" was found.
  This is probably a typing mistake. Fixing it will remove this message.

  Configuration Documentation:
  https://jestjs.io/docs/configuration
```

Still cant get this to work. I've tried:
 - The previous comment.
 - swcrc's `"sourceMaps": "inline"`
 - Versions of jest. swc, typescript, targets, etc
 
 I still get this:
```
 Method not implemented.

      17 |         throw new Error("Method not implemented.");
      18 |     }
    > 19 |
         | ^
      20 | }
```

**Comment by gethari** [comment]
@andreujuanc did you get it working ? for me I still cannot get it working
